name: Build and Test Docker Image

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    container: node:16-alpine
    steps:
      - name: Check out repo code
        uses: actions/checkout@v3
        
      - name: Build the docker image
        run: docker build -t simple-frontend .

      - name: Run the image and test the code
        run: docker run simple-frontend npm run test