name: Build and Test Docker Image

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build --file Dockerfile.dev --tag simple-frontend:$(date +%s)
    - name: Run tests
      run: docker run -e CI=true simple-frontend npm run test